permission: 'timsixth.sheep'
explozsivesheep: false
messages:
  nopermission: '&cYou dont have permission'
  disablesheep: '&cExplosive sheep is disabled!'
  sheepname: '&4Explosive Sheep'
  enablesheep: '&aExplosive sheep is enabled!'
  correctuse: '&cCorrect use: /togglesheep <on|off>'
  sheep_is_disabled: '&cExplosive sheep is already disabled'