author: timsixth (Idea by RokeR)
main: pl.timsixth.explosivesheep.ExplosiveSheepPlugin
version: '1.9.0'
name: T-ExplosiveSheep
api-version: 1.13
commands:
  togglesheep:
  explosivesheep:
  spawnsheep: